name: Simple CI

on:
  push:
    branches:
      - master
      - "feature/*"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - master
      - "feature/*"

jobs:
  android-build:
    name: Build mobile bundle (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install
    - name: Build with Gradle
      run: cd Android & gradle assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
       name: apk
       path: app/build/outputs/apk/release/app-release-unsigned.apk
#     - run: npx react-native bundle --entry-file react/index.native.js --platform android --bundle-output /tmp/android.bundle --reset-cache
 
